[styling.palette]
# Background
bg = "#303446"
surface = "#292c3c"
elevated = "#414559"

# Foreground & text
primary = "#c6d0f5"
fg = "#c6d0f5"
fg-muted = "#a5adce"

# Color palette
blue = "#8caaee"
green = "#a6d189"
red = "#e78284"
yellow = "#e5c890"
