[styling.palette]
# Background
bg = "#24273a"          # Base
surface = "#1e2030"     # Mantle
elevated = "#363a4f"    # Surface 0

# Foreground & text
fg = "#cad3f5"          # Text
fg-muted = "#a5adcb"    # Subtext 0

# Color palette
primary = "#c6a0f6"     # Mauve (Accent)
blue = "#b7bdf8"        # Lavender
green = "#8bd5ca"       # Teal
red = "#f5a97f"         # Peach
yellow = "#eed49f"      # Yellow
